StudyManifestTools: Check reference before export
Medable/mdctl pull request #485
Opened 2023-08-29 06:34 UTC by RudraNilBasu

Verifies that the tasks, steps and notifications that are associated
with a workflow is present in the environment when a workflow is
exported. Does not proceed with the export process if any of them are
not present

2023-08-29 10:08 UTC, dineshvenugopal requested changes

2023-08-29 10:08 UTC, dineshvenugopal commented on packages/mdctl-axon-tools/lib/StudyManifestTools.js
> +    }
Let's extract the validation functions into a new function

2023-08-29 11:49 UTC, dineshvenugopal submitted a review, later dismissed
LGTM

2023-08-30 05:53 UTC, mrahul17 approved these changes

2023-08-30 06:03 UTC, dineshvenugopal approved these changes

2023-08-30 06:38 UTC, merged